### ISSUE TITLE
Unable to post a Reflect poll

### ISSUE THREAD

**Issue by hansson94** [OfficeDev/Microsoft-Teams-App-Reflect#17]
Hello everyone!

I'm experiencing an issue with trying to post a Reflect poll in any teams chat.
I followed this walkthrough: https://github.com/OfficeDev/Microsoft-Teams-App-Reflect/wiki/Scenario-walk-thrus
After pressing the small icon in the messaging toolbar I get the same pop-up as displayed on the second picture.
I then press "Confirm" (The "Date" is set to today's date and "Time" is set to "Now"). After pressing confirm the pop-up disappears and nothing shows up in the chat.
I deployed the resources in Azure using the ARM template.

I would really appreciate some help here, thanks!

**Comment by Darren-Austin** [comment]
Hi @hansson94 - it sounds like the Reflect app might not be added to that specific chat or channel. In order to interact with chat participants, Reflect is implemented as a bot so (much like chatting with another user) you need to explicitly add Reflect to each team channel or chat you want to use it in. Once you add it to a team or a chat, anyone can use Reflect to create a Reflect poll to check in with the team.

For reference, here are instructions for adding an app to a specific channel or chat: https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-upload#upload-your-package-into-a-team-or-conversation-using-the-store

We are looking into a way for Reflect to proactively request to be added to a chat so that it's easier for users to access it. If we are successful at that we will update the code with the new functionality.

**Comment by hansson94** [comment]
Hello @Darren-Austin and thank you for the quick reply!
I added it to the app catalogue and from there added it to the team. This made it possible for other team owners to add it to their team as well. I now also tried to just add it straight to the team following the instructions in the link you provided (Upload your package into a team using the Apps tab) but unfortunately without success.

The app shows up when I look in manage team > apps, I can see Reflect poll popup by either mentioning reflect and write create reflect (@reflect create reflect) or pressing the icon in the bottom message bar. I did also have issues with multiple "Create Reflect" showing up when mentioning the bot so I redid everything from scratch, deleted the resource group in Azure, removed every trace of it from teams and re-added it, this time using the instructions you provided. But still, when pressing the confirm/send button nothing shows up.

**Comment by andreaslarssonliu** [comment]
Im experiencing the same issue, im not a good coder or anything so I will check internally with my organisation. Looking at application insights, im getting a forbidden.


Microsoft.Bot.Schema.ErrorResponseException at Microsoft.Bot.Connector.Conversations+<ReplyToActivityWithHttpMessagesAsync>d__10.MoveNext

Microsoft.Bot.Schema.ErrorResponseException at Reflection.Helper.DBHelper+<GetUserEmailId>d__13`1.MoveNext

**Comment by tcvall86** [comment]
Hello

Currently facing the same issue
So I drilled down in the exceptions through insights and found this exception before storage

Failed to acquire token for client credentials. (AADSTS700016: Application with identifier '<app id redacted>' was not found in the directory 'botframework.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant

Now before you say anything yes we have made sure that we have tried to deploy this with a tenant administrator

Here we have a similiar thread for bot builder

https://github.com/microsoft/BotBuilder-Samples/issues/1974

There is also a suggested fix to add additional key to the manifest
http://thewindowsupdate.com/2019/08/19/how-to-create-an-app-registration-in-azure-ad-for-a-bot-solution/

Will try that and see how it works

**Comment by andreaslarssonliu** [comment]
I got the acquire token issue at first, then I changed the appregistration to multitenant, that solved that issue.

The other issue was solved through adding the app to the team/chat in the "correct" way. You see it at 0.31 in the youtube video: https://www.youtube.com/watch?v=lRurlKbVGNg

Just installing the app wont make it work, you will get the icon and everything, but when you press publish it just fails. It fails because the app does not have permission on the team or chat.

A suggestion would be to add an errormessage for the user doing this, or in the instructions. Give the app permission to write in every team or chat?

**Comment by tcvall86** [comment]
> I got the acquire token issue at first, then I changed the appregistration to multitenant, that solved that issue.
> 
> The other issue was solved through adding the app to the team/chat in the "correct" way. You see it at 0.31 in the youtube video: https://www.youtube.com/watch?v=lRurlKbVGNg
> 
> Just installing the app wont make it work, you will get the icon and everything, but when you press publish it just fails. It fails because the app does not have permission on the team or chat.
> 
> A suggestion would be to add an errormessage for the user doing this, or in the instructions. Give the app permission to write in every team or chat?

Thanks for the heads up on the multi-tenant. The deployment doc is pretty ambigious about that, it does say multi-tenant but also that you can choose what is appropriate for your org

I will try that and get back

**Comment by Darren-Austin** [comment]
I appreciate the feedback here.  I made a few edits to the deployment instructions based on the feedback here.  Totally agree about the ambiguity about the "correct" way of adding a bot to a team.  Thanks for offering the pointer to the video that clarifies.
